language: python
sudo: false
python:
  - '3.5'
  - '3.6'
cache:
  directories:
    - $HOME/virtualenv/python*
    - $HOME/.cache/pip
install:
  - pip install -r requirements.txt --upgrade
  - pip install flake8 --upgrade
script:
  - flake8 .
  - python -m unittest -v tests